name: Generate Gradle Wrapper

on:
  workflow_dispatch:

jobs:
  wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Gradle
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle
      - name: Generate wrapper
        run: gradle wrapper
      - name: Commit wrapper
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add gradlew gradlew.bat gradle/wrapper
          git commit -m "Add Gradle Wrapper"
          git push
